# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voip_separate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voip_separate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voip_separate.proto\x12\x04voip\"A\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\"#\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2E\n\x0c\x41udioService\x12\x35\n\x0bStreamAudio\x12\x10.voip.AudioChunk\x1a\x10.voip.AudioChunk(\x01\x30\x01\x32<\n\x0c\x45ventService\x12,\n\x0cStreamEvents\x12\x0b.voip.Event\x1a\x0b.voip.Event(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voip_separate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=29
  _globals['_AUDIOCHUNK']._serialized_end=94
  _globals['_EVENT']._serialized_start=96
  _globals['_EVENT']._serialized_end=131
  _globals['_AUDIOSERVICE']._serialized_start=133
  _globals['_AUDIOSERVICE']._serialized_end=202
  _globals['_EVENTSERVICE']._serialized_start=204
  _globals['_EVENTSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
