# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvoip.proto\x12\x04voip\"Y\n\x0bVoIPMessage\x12!\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x10.voip.AudioChunkH\x00\x12\x1c\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x0b.voip.EventH\x00\x42\t\n\x07payload\"A\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\"#\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2A\n\x0bVoIPService\x12\x32\n\x06Stream\x12\x11.voip.VoIPMessage\x1a\x11.voip.VoIPMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOIPMESSAGE']._serialized_start=20
  _globals['_VOIPMESSAGE']._serialized_end=109
  _globals['_AUDIOCHUNK']._serialized_start=111
  _globals['_AUDIOCHUNK']._serialized_end=176
  _globals['_EVENT']._serialized_start=178
  _globals['_EVENT']._serialized_end=213
  _globals['_VOIPSERVICE']._serialized_start=215
  _globals['_VOIPSERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
